# Generated by Django 4.2.23 on 2025-12-17 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coding_assistant', '0002_codesnippet_is_public_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_snippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='parent_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='coding_assistant.codesnippet'),
        ),
    ]
