# Generated by Django 4.2.23 on 2025-12-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_assistant', '0004_badge_userbadge_userprofile_userbadge_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingchallenge',
            name='generation_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingchallenge',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codingchallenge',
            name='test_criteria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
